package com.servicedesk.service;
import com.servicedesk.model.*; import com.servicedesk.repo.*; import com.servicedesk.dto.*; import org.springframework.stereotype.Service; import java.time.*; import java.util.*;
@Service public class TicketService {
 private final TicketRepository tickets; private final UserRepository users; private final SlaRuleRepository slas; private final StatusHistoryRepository history;
 public TicketService(TicketRepository t,UserRepository u,SlaRuleRepository s,StatusHistoryRepository h){tickets=t;users=u;slas=s;history=h;}
 public Map<String,Object> view(Ticket t){Map<String,Object> m=new LinkedHashMap<>(); m.put("ticketId",String.format("TKT-%03d",t.ticketId)); m.put("id",t.ticketId);m.put("title",t.title);m.put("description",t.description);m.put("category",t.category);m.put("priority",t.priority);m.put("status",t.status);m.put("userId",t.userId);m.put("createdAt",t.createdAt); var u=users.findById(t.userId).orElse(null); m.put("raisedBy",u==null?"Unknown":u.name); var s=slas.findById(t.priority).orElse(null); if(s!=null){m.put("responseDueAt",t.createdAt.plusHours(hours(s.responseTimeLimit)));m.put("resolutionDueAt",t.createdAt.plusHours(hours(s.resolutionTimeLimit)));} m.put("resolvedAt",(t.status.equals("Resolved")||t.status.equals("Closed"))?history.findByTicketIdOrderByChangedAtAsc(t.ticketId).stream().filter(x->x.newStatus.equals("Resolved")||x.newStatus.equals("Closed")).map(x->x.changedAt).reduce((a,b)->b).orElse(null):null);m.put("history",history.findByTicketIdOrderByChangedAtAsc(t.ticketId));return m;}
 private long hours(String x){try{return Long.parseLong(x.replaceAll("[^0-9]",""));}catch(Exception e){return 0;}}
 public List<Map<String,Object>> all(){return tickets.findAll().stream().sorted(Comparator.comparing((Ticket x)->x.createdAt).reversed()).map(this::view).toList();}
 public List<Map<String,Object>> mine(Integer id){return tickets.findByUserIdOrderByCreatedAtDesc(id).stream().map(this::view).toList();}
 public Map<String,Object> create(TicketRequest r){if(!users.existsById(r.userId()))throw new RuntimeException("User not found"); Ticket t=new Ticket();t.title=r.title();t.description=r.description();t.category=r.category();t.priority=r.priority();t.status="New";t.userId=r.userId();tickets.save(t);StatusHistory h=new StatusHistory();h.ticketId=t.ticketId;h.newStatus="New";history.save(h);return view(t);}
 public Map<String,Object> update(Integer id,String status){Ticket t=tickets.findById(id).orElseThrow();String old=t.status;t.status=status;tickets.save(t);if(!Objects.equals(old,status)){StatusHistory h=new StatusHistory();h.ticketId=id;h.oldStatus=old;h.newStatus=status;history.save(h);}return view(t);}
}
